{% set build = 0 %}
{% set version = '0.10.0.post1' %}

package:
  name: bidict
  version: {{version}}

about:
  home: https://github.com/jab/bidict
  license: ISC License (ISCL)
  summary: "Efficient, Pythonic bidirectional map implementation and related functionality."

source:
  fn: bidict-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/b/bidict/bidict-{{version}}.tar.gz
  md5: 786ba5144c3253519ed7d908b4103dc1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

build:
  number: {{build}}
  script: python setup.py install
