{%set build = 0 %}

package:
  name: bidict
  version: !!str 0.3.1

about:
  home: https://github.com/jab/bidict
  license: ISC License (ISCL)
  summary: "2-way dict with convenient slice syntax: d[65] = 'A' -> d[:'A'] == 65"

source:
  fn: bidict-0.3.1.tar.gz
  url: https://pypi.python.org/packages/source/b/bidict/bidict-0.3.1.tar.gz
  md5: ae55b33fc19a1e47b5f16c96ed841443

requirements:
  build:
    - python
    - setuptools

  run:
    - python

build:
  number: {{build}}
  script: python setup.py install
